name: Pull Request

on:
  pull_request:

jobs:
  test-semantic-release:
    name: Release dry-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Config git
        run: |
          git config --local user.email "30906710+traefiker@users.noreply.github.com"
          git config --local user.name "traefiker"

      - name: Create dry branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          branch: "dry"

      - name: Checkout dry branch
        uses: actions/checkout@v2
        with:
          ref: dry

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Dry run
        id: dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const script = require('./semantic-release-dry.js')
            return await script({require})

      - name: Back to code
        uses: actions/checkout@v2

      - name: Clear dry branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{secrets.GH_TOKEN}}
          branches: dry

      - name: "Release notes in PR description"
        uses: actions/github-script@v6
        with:
          script: |
            const nextBody = github.event.pull_request.body + '\n\n#Release notes preview\n\n<details>\n\n' + steps.dry-run.outputs.result + '\n</details>';
            github.rest.pulls.update({
              pull_number: github.event.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: nextBody
            })
