name: Pull Request

on:
  pull_request:

jobs:
  test-semantic-release:
    name: Release dry-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Config git
        run: |
          git config --local user.email "30906710+traefiker@users.noreply.github.com"
          git config --local user.name "traefiker"

      - name: Create dry branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          branch: 'dry'

      - name: Checkout dry branch
        uses: actions/checkout@v2
        with:
          ref: dry
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Dry run
        id: semantic-dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "::echo::on"
          echo "::set-output name=note::$(unset GITHUB_ACTIONS && npx semantic-release --dry-run --no-ci)"
      
      - name: Back to code
        uses: actions/checkout@v2
      
      - name: Clear dry branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{secrets.GH_TOKEN}}
          branches: dry

      - name: 'Comment with log on PR'
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            github.issues.createComment({ issue_number, owner, repo, body: `${{steps.semantic-dry-run.outputs.note}}` });