name: Pull Request

on:
  pull_request:

jobs:
  test-semantic-release:
    name: Release dry-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Config git
        run: |
          git config --local user.email "30906710+traefiker@users.noreply.github.com"
          git config --local user.name "traefiker"

      - name: Checkout alpha branch locally
        run: git checkout -b alpha
      - name: Dry run
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: unset GITHUB_ACTIONS && npx semantic-release --dry-run --no-ci
      - name: Back to code
        uses: actions/checkout@v2
      - name: Clear alpha branch
        run: git branch -D alpha