name: Pull Request

on:
  pull_request:

jobs:
  test-semantic-release:
    name: Release dry-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Config git
        run: |
          git config --local user.email "30906710+traefiker@users.noreply.github.com"
          git config --local user.name "traefiker"

      - name: Create dry branch
        uses: actions/github-script@v6
        with:
          script: |
            try {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/heads/dry'
              });
            } catch (e) {}
            try {
              await github.rest.git.createRef({
                ref: 'refs/heads/dry',
                sha: context.sha,
                ...context.repo
              })
            } catch (e) {}

      - name: Checkout dry branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          ref: dry

      - name: Squash commits into PR title
        run: |
          git reset --soft HEAD^
          git commit -m '${{ github.event.pull_request.title }}'
          git push --force

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Dry run
        id: dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const script = require('./semantic-release-dry.js')
            return await script({require})

      - name: Back to code
        uses: actions/checkout@v2

      - name: Clear dry branch
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/heads/dry'
            });

      - name: "Release notes preview comment"
        uses: actions/github-script@v6
        with:
          script: |
            const header = `# :spiral_notepad: Release notes preview`;
            const nextBody = ${{ github.event.pull_request.body }} + '\n\n' + header + '\n\n<details>\n\n' + `${{ steps.dry-run.outputs.result }}` + '\n</details>';
            await github.rest.issues.createComment({
              issue_number: ${{ github.event.pull_request.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: nextBody
            })
