name: Pull Request

on:
  pull_request:

jobs:
  test-semantic-release:
    name: Release dry-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Config git
        run: |
          git config --local user.email "30906710+traefiker@users.noreply.github.com"
          git config --local user.name "traefiker"

      - name: Create dry branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          branch: "dry"

      - name: Checkout dry branch
        uses: actions/checkout@v2
        with:
          ref: dry

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Dry run
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          unset GITHUB_ACTIONS
          echo "::echo::on"
          echo "NOTES<<EOF" >> $GITHUB_ENV
          npx semantic-release --dry-run --no-ci >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Back to code
        uses: actions/checkout@v2

      - name: Clear dry branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{secrets.GH_TOKEN}}
          branches: dry

      - name: "Comment with log on PR"
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{github.event.number}}
          body: |
            # Release preview

            ${{env.NOTES}}
