name: Pull Request

on:
  pull_request:
    types: ["opened", "reopened", "edited", "synchronize"]

jobs:
  faency:
    name: Lint PR Title
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Run commitlint
        run: echo ${{ github.event.pull_request.title }} | npx commitlint --config ./package.json
