name: Pull Request

on:
  pull_request_target:
    types: ["opened", "reopened", "edited", "synchronize"]

jobs:
  faency:
    name: Lint PR Title
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Semantic pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        uses: amannn/action-semantic-pull-request@v4.2.0
